version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.0
  aws-ecr: circleci/aws-ecr@3.1.0
  kubernetes: circleci/kubernetes@0.3.0

workflows:
  deployment:
    jobs:
      - aws-ecr/build_and_push_image:
          name: build-and-push-image
          account-url: AWS_ECR_URL
          region: AWS_DEFAULT_REGION
          repo: simplelearnapp1
          dockerfile: Dockerfile
          tag: "15"
          # Uncomment if the repository does not yet exist
          # create-repo: true
      - aws-eks/install-helm-chart:
          chart: "829804546595.dkr.ecr.eu-central-1.amazonaws.com/simplelearnapp1:15"
          cluster-name: terraform-eks-demo
          release-name: nginx-release
          requires:
            - build-and-push-image
