version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.0
  aws-ecr: circleci/aws-ecr@3.1.0
  kubernetes: circleci/kubernetes@0.3.0

workflows:
  deployment:
    jobs:
      - aws-ecr/build_and_push_image:
          name: build-and-push-image
          account-url: AWS_ECR_URL
          region: AWS_DEFAULT_REGION
          repo: simplelearnapp1
          dockerfile: Dockerfile
          tag: "11"
          # Uncomment if the repository does not yet exist
          # create-repo: true
      - aws-eks/install-helm-chart:
          chart: AWS_ECR_URL/simplelearnapp1:10
          cluster-name: terraform-eks-demo
          release-name: grafana-release
