version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.0
  aws-ecr: circleci/aws-ecr@3.1.0
  kubernetes: circleci/kubernetes@0.3.0
  helm: circleci/helm@0.2.3

jobs:
  install-helm-custom-chart:
    executor: aws-eks/python3
    steps:
      - run:
          command: |
            apt-get update --fix-missing
            apt-get install -y apt-transport-https ca-certificates software-properties-common
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
            apt-key fingerprint 0EBFCD88
            add-apt-repository \
              "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
              $(lsb_release -cs) \
              stable"
            apt-get update
            apt-get install -y docker-ce
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_URL
          region: AWS_DEFAULT_REGION
          repo: simplelearnapp1
          dockerfile: Dockerfile
          tag: "stable"
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: terraform-eks-demo
          install-kubectl: true
      - helm/install-helm-on-cluster:
          enable-cluster-wide-admin-access: false
      - run:
          name: install custom helm chart
          command: |
            helm create cstmnginx
            mv cstmnginx/values.yaml cstmnginx/values.yaml.template
            cat cstmnginx/values.yaml.template |\
               sed "s|repository: nginx|repository: 829804546595.dkr.ecr.eu-central-1.amazonaws.com/simplelearnapp1|g" > cstmnginx/values.yaml
            helm install ./cstmnginx

workflows:
  deployment:
    jobs:
      - install-helm-custom-chart:
          name: install-helm-custom-chart
