version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.0
  aws-ecr: circleci/aws-ecr@3.1.0
  kubernetes: circleci/kubernetes@0.3.0
  helm: circleci/helm@0.2.3

jobs:
  push-image-install-helm-chart:
    executor: aws-eks/python3
    steps:
      - setup_remote_docker
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_URL
          region: AWS_DEFAULT_REGION
          repo: simplelearnapp1
          dockerfile: Dockerfile
          tag: "stable"
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: terraform-eks-demo
          install-kubectl: true
      - helm/install-helm-on-cluster:
          enable-cluster-wide-admin-access: false
      - run:
          name: install custom helm chart
          command: |
            helm install ./cstmnginx --set image.repository=829804546595.dkr.ecr.eu-central-1.amazonaws.com/simplelearnapp1 --generate-name
#            mv cstmnginx/values.yaml cstmnginx/values.yaml.template
#            cat cstmnginx/values.yaml.template |\
#               sed "s|repository: nginx|repository: 829804546595.dkr.ecr.eu-central-1.amazonaws.com/simplelearnapp1|g" > cstmnginx/values.yaml
#           helm repo add cstmnginx https://kubernetes-charts.storage.googleapis.com
#            helm install cstmnginx

workflows:
  nginx_deployment:
    jobs:
      - push-image-install-helm-chart:
          name: push-image-install-helm-chart
