version: 2.1

orbs:
  aws-eks: circleci/aws-eks@0.2.0
  aws-ecr: circleci/aws-ecr@3.1.0
  kubernetes: circleci/kubernetes@0.3.0
  helm: circleci/helm@0.2.3

jobs:
  install-helm-custom-chart:
    executor: aws-eks/python3
    steps:
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: terraform-eks-demo
          install-kubectl: true
      - helm/install-helm-on-cluster:
          enable-cluster-wide-admin-access: true
      - run:
          name: install custom helm chart
          command: |
            helm install ./mychart

workflows:
  deployment:
    jobs:
      - aws-ecr/build_and_push_image:
          name: build-and-push-image
          account-url: AWS_ECR_URL
          region: AWS_DEFAULT_REGION
          repo: simplelearnapp1
          dockerfile: Dockerfile
          tag: "23"
          # Uncomment if the repository does not yet exist
          # create-repo: true
      - install-helm-custom-chart:
          name: install-helm-custom-chart
          requires:
            - build-and-push-image
#      - aws-eks/install-helm-chart:
#          chart: "https://829804546595.dkr.ecr.eu-central-1.amazonaws.com/simplelearnapp1/17"
#          cluster-name: terraform-eks-demo
#          aws-region: eu-central-1
#          release-name: nginx-release
#          requires:
#            - build-and-push-image
